import { supabase } from '../../lib/supabase';

export type OrderData = {
  order_id: string; // varchar
  service_id: string; // varchar
  customer_id: string; // uuid
  order_status: string; // varchar
  delivery_mode: string; // varchar
  order_date_time: string; // timestamp (ISO string)
  completed_date_time: string | null; // timestamp (ISO string or null)
  specification: string; // varchar
  page_size: string; // varchar
  quantity: number; // numeric
  priority_level: number; // numeric
};

export async function createOrder(order: Omit<OrderData, 'order_id'>) {
  const { data, error } = await supabase
    .from('orders_duplicate')
    .insert([
      {
        // order_id will be auto-generated UUID
        // display_id will be auto-generated by trigger
        customer_id: order.customer_id,
        total_amount: 0, // Will be updated when quote is provided
        currency: 'PHP',
        order_specs: {
          service_id: order.service_id,
          specification: order.specification,
          page_size: order.page_size,
          quantity: order.quantity,
          priority_level: order.priority_level,
          delivery_mode: order.delivery_mode,
          order_date_time: order.order_date_time,
          completed_date_time: order.completed_date_time,
        },
        status: 'awaiting_payment', // Map from order_status
      },
    ])
    .select()
    .single();
  if (error) {
    console.error('Order creation failed:', error);
    return { success: false, error };
  }
  return { success: true, data };
}
