/**
 * Action handler: validate_and_create_service
 *
 * Validates a service name and creates a new printing service in the database.
 * This action is used in the admin-add-service flow when admin chooses an existing category.
 *
 * @description
 * - Validates that service name is provided and not empty
 * - Checks if service name already exists in the same category (case-insensitive)
 * - Creates new service with status INACTIVE
 * - Sets created_by to admin user ID
 * - Optionally sets description if provided in context
 * - Display ID is automatically generated by trigger (SRV-000000 format)
 *
 * @param params.actionNode - The action node from the flow definition
 * @param params.context - Current session context containing service_name, category_id, and optionally description
 * @param params.sessionId - Current chat session ID
 * @param params.customerId - Admin user ID (from session)
 *
 * @returns ActionExecutionResult with success/error message
 */

import { getAdminUserId } from '@features/chat/utils/admin/getAdminUserId';
import { supabase } from '@lib/supabase';
import type {
  ActionExecutionParams,
  ActionExecutionResult,
} from '@features/chat/types';

export async function validateAndCreateService(
  params: ActionExecutionParams
): Promise<ActionExecutionResult> {
  const { context } = params;
  const messages: Array<{
    id: string;
    role: 'printy';
    text: string;
    ts: number;
  }> = [];

  try {
    const serviceName = String(context.service_name || '').trim();
    const categoryId = context.category_id || context.selected_category;

    // Validate service name
    if (!serviceName || serviceName.length === 0) {
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: 'Service name cannot be empty. Please provide a valid service name.',
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    // Check minimum length
    if (serviceName.length < 2) {
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: 'Service name must be at least 2 characters long. Please provide a longer name.',
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    // Validate category_id
    // Try both selected_category (from quick reply) and category_id (from context)
    const actualCategoryId = categoryId || context.selected_category;
    if (!actualCategoryId) {
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: 'Category information is missing. Please try selecting a category again.',
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    // Check if service name already exists in the same category (case-insensitive)
    const { data: existingService, error: checkError } = await supabase
      .from('printing_services')
      .select('service_id, service_name, category_id')
      .eq('category_id', actualCategoryId)
      .ilike('service_name', serviceName)
      .maybeSingle();

    if (checkError && checkError.code !== 'PGRST116') {
      // PGRST116 is "not found" which is expected
      console.error(
        '[validateAndCreateService] Error checking existing service:',
        checkError
      );
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: 'An error occurred while validating the service name. Please try again.',
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    if (existingService) {
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: `A service with the name "${serviceName}" already exists in this category. Please choose a different name.`,
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    // Get admin user ID
    const adminUserId = await getAdminUserId();

    // Get description from context (optional)
    // Check action_config for description_key, otherwise use default 'description'
    const config = params.actionNode?.action_config as any;
    const descriptionKey = config?.description_key || 'description';
    const descriptionValue = context[descriptionKey] || context.description;
    const description = descriptionValue
      ? String(descriptionValue).trim()
      : null;

    // Create the service with status INACTIVE
    // Display ID will be automatically generated by trigger (SRV-000000 format)
    const { data: newService, error: insertError } = await supabase
      .from('printing_services')
      .insert({
        service_name: serviceName,
        category_id: actualCategoryId,
        description: description || null,
        status: 'inactive', // Set to INACTIVE as per requirements
        created_by: adminUserId,
        updated_by: adminUserId,
      })
      .select('service_id, service_name, display_id, category_id')
      .single();

    if (insertError) {
      console.error(
        '[validateAndCreateService] Error creating service:',
        insertError
      );
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: 'Failed to create the service. Please try again.',
        ts: Date.now(),
      });
      return {
        messages,
      };
    }

    // Success message
    const descriptionText = description ? `\nDescription: ${description}` : '';
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: `Service "${serviceName}" has been created successfully!${descriptionText}\nService ID: ${newService.display_id || newService.service_id}\n\nNote: The service is set to INACTIVE status. You can activate it later from the portfolio page.`,
      ts: Date.now(),
    });

    // Store service info in context for potential future use
    return {
      messages,
      context: {
        created_service_id: newService.service_id,
        created_service_name: newService.service_name,
        created_service_display_id: newService.display_id,
      },
    };
  } catch (error) {
    console.error('[validateAndCreateService] Unexpected error:', error);
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: 'An unexpected error occurred while creating the service. Please try again.',
      ts: Date.now(),
    });
    return {
      messages,
    };
  }
}
