/**
 * Action handler: create_inquiry
 *
 * Creates a support ticket/inquiry for customer issues or questions.
 * The inquiry is stored in the inquiries table and assigned a unique display ID
 * for tracking purposes.
 *
 * @description
 * - Creates an inquiry record with customer-provided details
 * - Automatically generates a display ID for easy reference
 * - Sets initial status to 'new' for admin review
 * - Updates session metadata with inquiry_id
 * - Returns success message with ticket ID
 *
 * @param params.actionNode - The action node from the flow definition
 * @param params.context - Current session context containing inquiry_type and issue_details
 * @param params.customerId - Customer creating the inquiry
 * @param params.sessionId - Current chat session ID
 *
 * @returns ActionExecutionResult with success message containing ticket display ID
 *
 * @example
 * ```json
 * // Flow definition usage
 * {
 *   "id": "create_ticket",
 *   "type": "action",
 *   "action": "create_inquiry",
 *   "action_config": {
 *     "type_key": "inquiry_type",
 *     "details_key": "issue_details"
 *   },
 *   "next": "success_message"
 * }
 * ```
 *
 * @remarks
 * - The display_id is auto-generated by the database
 * - Falls back to inquiry_id if display_id is not available
 * - Issue details are stored as plain text (encryption TBD)
 */
import { getAllAdminIds } from '@features/chat/utils/admin/getAdminUserId';
import { supabase } from '@lib/supabase';
import type {
  ActionExecutionParams,
  ActionExecutionResult,
} from '@features/chat/types';
import { ChatEndService } from '../../services/ChatEndService';
import { insertMessageV2 } from '@features/chat/api/jsonbChatFlowApi';

export async function createInquiry(
  params: ActionExecutionParams
): Promise<ActionExecutionResult> {
  console.log('[createInquiry] Action started with params:', params);

  const { actionNode, context, customerId, sessionId } = params;
  const messages: Array<{
    id: string;
    role: 'printy';
    text: string;
    ts: number;
  }> = [];

  const config = actionNode.action_config as any;
  const typeKey = config.type_key || 'inquiry_type';
  const detailsKey = config.details_key || 'issue_details';
  const orderIdKey = config.order_id_key || 'order_id';

  const inquiryType = String(context[typeKey] || 'other');
  const issueDetails = String(context[detailsKey] || '');
  const orderDisplayId = context[orderIdKey] || null;

  console.log('[createInquiry] Extracted values:', {
    inquiryType,
    issueDetails,
    orderDisplayId,
  });

  if (!issueDetails) {
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: 'Please provide issue details.',
      ts: Date.now(),
    });
    return { messages };
  }

  // If customer provided an order display_id (from quick reply selection), get the actual order UUID
  let actualOrderId = null;
  if (orderDisplayId && orderDisplayId !== 'no_order') {
    const { data: orderData } = await supabase
      .from('orders')
      .select('order_id')
      .eq('display_id', orderDisplayId)
      .eq('customer_id', customerId) // Get order that belongs to this customer
      .single();

    if (orderData) {
      actualOrderId = orderData.order_id;
    }
    // No need for validation error since we're only showing customer's own orders via quick replies
  }
  // If orderDisplayId is 'no_order', the issue is not related to a specific order - proceed without linking

  // Create inquiry in v2 table - let database auto-generate display_id
  console.log('[createInquiry] Creating inquiry with data:', {
    customer_id: customerId,
    inquiry_type: inquiryType,
    inquiry_status: 'new',
    session_id: sessionId,
    order_id: actualOrderId,
    updated_by: customerId,
  });

  const { data: inquiryData, error } = await supabase
    .from('inquiries_v2')
    .insert({
      customer_id: customerId,
      inquiry_type: inquiryType,
      inquiry_status: 'new',
      session_id: sessionId,
      order_id: actualOrderId, // Store actual order UUID if found
      updated_by: customerId, // Track that customer created the ticket
    })
    .select('inquiry_id, display_id')
    .single();

  if (error) {
    console.error('[createInquiry] Failed to create inquiry:', error);
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: "Couldn't create the ticket. Try again later.",
      ts: Date.now(),
    });
    return { messages };
  }

  console.log('[createInquiry] Inquiry created successfully:', inquiryData);

  const inquiryId = inquiryData?.inquiry_id;
  let displayId = inquiryData?.display_id;

  console.log('[createInquiry] Starting notification creation process...');

  // Create notifications for admins about the new ticket
  try {
    // Get customer name for the notification
    const { data: customerData } = await supabase
      .from('customer')
      .select('first_name, last_name')
      .eq('customer_id', customerId)
      .single();

    const customerName = customerData
      ? `${customerData.first_name || ''} ${customerData.last_name || ''}`.trim() ||
        'Customer'
      : 'Customer';

    console.log('[createInquiry] Got customer name:', customerName);

    // Get all admin users
    const adminIds = await getAllAdminIds();
    console.log('[createInquiry] Got admin IDs:', adminIds);

    if (adminIds.length > 0) {
      // Create notification for each admin
      const notifications = adminIds.map(adminId => ({
        customer_id: adminId,
        source_type: 'ticket',
        source_id: inquiryId,
        title: 'New Support Ticket',
        message: `New support ticket #${displayId || inquiryId?.substring(0, 8)} created by ${customerName}.`,
        type: 'warning',
        category: 'ticket',
      }));

      console.log(
        '[createInquiry] Creating admin notifications:',
        notifications
      );

      const { error: notifError } = await supabase
        .from('notifications')
        .insert(notifications);

      if (notifError) {
        console.error(
          '[createInquiry] Error creating admin notifications:',
          notifError
        );
      } else {
        console.log(
          '[createInquiry] Created notifications for',
          adminIds.length,
          'admins'
        );
      }
    }
  } catch (notifErr) {
    console.error('[createInquiry] Error in notification creation:', notifErr);
    // Don't fail the whole action if notifications fail
  }

  if (!inquiryId) {
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: "Couldn't create the ticket. Try again later.",
      ts: Date.now(),
    });
    return { messages };
  }

  // Fallback: use inquiry_id if display_id is not available
  if (!displayId) {
    displayId = inquiryId;
  }

  // Store issue details in chat_messages_v2 for conversation history using proper encryption
  await insertMessageV2({
    sessionId,
    text: issueDetails,
    role: 'customer',
    nodeId: 'collect_details',
  });

  // Update session with inquiry_id FK and metadata
  await supabase
    .from('chat_sessions_v2')
    .update({
      inquiry_id: inquiryId,
      metadata: {
        ...context,
        inquiry_id: inquiryId,
        title: `Issue: ${inquiryType}`,
        issue_preview: issueDetails.substring(0, 100), // Store preview for quick display
      } as any,
    })
    .eq('session_id', sessionId);

  // Success message matching issueTicketFlow.ts
  let successText = `Your support ticket has been created! Here is your Ticket ID: ${displayId}\n\nOur team will review your issue and get back to you as soon as possible. You can track the status of your ticket in your dashboard.\n\nWe appreciate your patience!`;

  // Add order information if successfully linked
  if (orderDisplayId && actualOrderId) {
    successText = `Your support ticket has been created and linked to Order ${orderDisplayId}! Here is your Ticket ID: ${displayId}\n\nOur team will review your issue and get back to you as soon as possible. You can track the status of your ticket in your dashboard.\n\nWe appreciate your patience!`;
  }

  messages.push({
    id: crypto.randomUUID(),
    role: 'printy',
    text: successText,
    ts: Date.now(),
  });

  // ✅ FIX: Don't insert message here - JsonbFlowProcessor caller will handle it
  // This prevents duplicate messages in the database

  return { messages };
}

/**
 * Action handler: end_customer_chat
 *
 * Ends a customer's chat session using the unified ChatEndService.
 * This ensures consistent behavior across all end chat operations.
 *
 * @param params.actionNode - The action node from the flow definition
 * @param params.context - Current session context
 * @param params.customerId - Customer ending the chat
 * @param params.sessionId - Current chat session ID
 *
 * @returns ActionExecutionResult with end chat message
 */
export async function endCustomerChat(
  params: ActionExecutionParams
): Promise<ActionExecutionResult> {
  const { customerId, sessionId } = params;
  const messages: Array<{
    id: string;
    role: 'printy';
    text: string;
    ts: number;
  }> = [];

  try {
    // Use the unified service to end the chat
    const result = await ChatEndService.endChatSession({
      sessionId,
      userId: customerId,
      userType: 'customer',
      endMessage: 'Thank you for chatting with us. Have a great day!',
    });

    if (!result.success) {
      console.error('Failed to end customer chat:', result.error);
      messages.push({
        id: crypto.randomUUID(),
        role: 'printy',
        text: "I'm having trouble ending the chat. Please try again.",
        ts: Date.now(),
      });
      return { messages };
    }

    // Success message - this will be added by the service, so we don't need to add another
    return { messages };
  } catch (error) {
    console.error('Error in endCustomerChat:', error);
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: 'Something went wrong. Please try again.',
      ts: Date.now(),
    });
    return { messages };
  }
}
