/**
 * Action handler: create_inquiry
 *
 * Creates a support ticket/inquiry for customer issues or questions.
 * The inquiry is stored in the inquiries table and assigned a unique display ID
 * for tracking purposes.
 *
 * @description
 * - Creates an inquiry record with customer-provided details
 * - Automatically generates a display ID for easy reference
 * - Sets initial status to 'new' for admin review
 * - Updates session metadata with inquiry_id
 * - Returns success message with ticket ID
 *
 * @param params.actionNode - The action node from the flow definition
 * @param params.context - Current session context containing inquiry_type and issue_details
 * @param params.customerId - Customer creating the inquiry
 * @param params.sessionId - Current chat session ID
 *
 * @returns ActionExecutionResult with success message containing ticket display ID
 *
 * @example
 * ```json
 * // Flow definition usage
 * {
 *   "id": "create_ticket",
 *   "type": "action",
 *   "action": "create_inquiry",
 *   "action_config": {
 *     "type_key": "inquiry_type",
 *     "details_key": "issue_details"
 *   },
 *   "next": "success_message"
 * }
 * ```
 *
 * @remarks
 * - The display_id is auto-generated by the database
 * - Falls back to inquiry_id if display_id is not available
 * - Issue details are stored as plain text (encryption TBD)
 */
import { supabase } from '@lib/supabase';
import { insertMessage } from '@features/chat/helpers/flowHelpers';
import type { ActionExecutionParams, ActionExecutionResult } from '@features/chat/types';

export async function createInquiry(params: ActionExecutionParams): Promise<ActionExecutionResult> {
  const { actionNode, context, customerId, sessionId } = params;
  const messages: Array<{ id: string; role: 'printy'; text: string; ts: number }> = [];

  const config = actionNode.action_config as any;
  const typeKey = config.type_key || 'inquiry_type';
  const detailsKey = config.details_key || 'issue_details';

  const inquiryType = String(context[typeKey] || 'other');
  const issueDetails = String(context[detailsKey] || '');

  if (!issueDetails) {
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: 'Please provide issue details.',
      ts: Date.now(),
    });
    return { messages };
  }

  // Create inquiry directly - let database auto-generate display_id
  const { data: inquiryData, error } = await supabase
    .from('inquiries')
    .insert({
      customer_id: customerId,
      inquiry_type: inquiryType,
      inquiry_message_enc: issueDetails, // Store as plain text for now
      inquiry_status: 'new',
      session_id: sessionId,  // ✅ Set FK directly
    })
    .select('inquiry_id, display_id')
    .single();

  if (error) {
    console.error('Failed to create inquiry:', error);
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: "Couldn't create the ticket. Try again later.",
      ts: Date.now(),
    });
    return { messages };
  }

  const inquiryId = inquiryData?.inquiry_id;
  let displayId = inquiryData?.display_id;

  if (!inquiryId) {
    messages.push({
      id: crypto.randomUUID(),
      role: 'printy',
      text: "Couldn't create the ticket. Try again later.",
      ts: Date.now(),
    });
    return { messages };
  }

  // Fallback: use inquiry_id if display_id is not available
  if (!displayId) {
    displayId = inquiryId;
  }

  // Update session with inquiry_id FK and metadata
  await supabase
    .from('chat_sessions_v2')
    .update({
      inquiry_id: inquiryId,  // ✅ Set FK
      metadata: {
        ...context,
        inquiry_id: inquiryId,  // Keep in metadata for backward compat
      } as any,
    })
    .eq('session_id', sessionId);

  // Success message matching issueTicketFlow.ts
  let successText = `Your support ticket has been created! Here is your Ticket ID: ${displayId}\n\nOur team will review your issue and get back to you as soon as possible. You can track the status of your ticket in your dashboard.\n\nWe appreciate your patience!`;

  messages.push({
    id: crypto.randomUUID(),
    role: 'printy',
    text: successText,
    ts: Date.now(),
  });

  await insertMessage({
    sessionId,
    text: successText,
    role: 'printy',
    nodeId: actionNode.action,
  });

  return { messages };
}
